"""First-sector markers that flag a builder image so it is never presented as
field evidence."""

from __future__ import annotations

from pathlib import Path

# Examiner-facing wording. A builder image is one this tool generated to
# exercise the parsers; it was not imaged from a device.
BUILDER_IMAGE_BANNER = (
    "Builder image. These bytes were generated by this tool to exercise the "
    "parsers; they were not imaged from a device. Not a field acquisition."
)
# Byte markers written into builder images by engine/app/verification/*. The
# literal text of a marker is an internal detection token shown to no one; the
# examiner reads BUILDER_IMAGE_BANNER.
_MARKERS: tuple[bytes, ...] = (
    b"PRAMAAN-BUILDER-IMG-HIKVISION",
    b"CPPLUS-BUILDER-IMG",
    b"Honeywell HWDVR builder image",
)


def detect_acquisition_class(path: Path) -> dict | None:
    """Return acquisition-class metadata when the image carries a builder marker,
    else None (treated as a normal acquisition)."""
    try:
        with path.open("rb") as handle:
            head = handle.read(512)
    except OSError:
        return None
    if not head:
        return None
    for marker in _MARKERS:
        if marker in head:
            return {
                "class": "builder_image",
                "authenticity": "tool_generated",
                "message": BUILDER_IMAGE_BANNER,
            }
    return None
