import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { toast } from "sonner";
import { useCaseContext } from "@/context/CaseContext";
import { api, type IdentificationReport } from "@/lib/api";
import {
  capabilityTierLabel,
  recoveryAdapterLabel,
  validationScopeLabel,
} from "@/lib/integrity";
import { ConfidenceBadge } from "@/components/forensic/ConfidenceBadge";
import { HexViewer } from "@/components/forensic/HexViewer";
import { Button } from "@/components/ui/button";
import { PageHeader } from "@/components/visily/PageHeader";
import { formatBytes, formatOffset } from "@/lib/utils";

// A DHAV or NAL stream can have thousands of leaf nodes; the tree is a preview,
// not an inventory. Cap the rendered rows so the page stays usable.
const LAYOUT_TREE_LIMIT = 60;

type StructureNode = {
  label: string;
  offset: number;
  size: number;
  type: string;
  meta?: Record<string, unknown>;
  children?: StructureNode[];
};

function flattenNodes(
  nodes: StructureNode[],
  depth = 0,
): Array<{ node: StructureNode; depth: number }> {
  const flat: Array<{ node: StructureNode; depth: number }> = [];

  for (const node of nodes) {
    flat.push({ node, depth });

    if (node.children?.length) {
      flat.push(...flattenNodes(node.children, depth + 1));
    }
  }

  return flat;
}

export function CaseDeviceIdPage() {
  const { caseId, workspace, refresh } = useCaseContext();

  const [deviceId, setDeviceId] = useState("");

  const [report, setReport] = useState<IdentificationReport | null>(null);

  const [scanning, setScanning] = useState(false);

  const [hexOffset, setHexOffset] = useState(0);
  const [structure, setStructure] = useState<StructureNode[]>([]);
  const [selectedNode, setSelectedNode] = useState<StructureNode | null>(null);

  const evidence = workspace?.evidence ?? [];

  useEffect(() => {
    if (evidence[0] && !deviceId) {
      setDeviceId(evidence[0].id);

      setReport(evidence[0].identification ?? null);
    }
  }, [evidence, deviceId]);

  useEffect(() => {
    if (!deviceId) {
      setStructure([]);
      return;
    }
    void api
      .deviceStructure(deviceId)
      .then((result) => {
        setStructure(result.nodes as StructureNode[]);
        setSelectedNode((result.nodes[0] ?? null) as StructureNode | null);
      })
      .catch(() => setStructure([]));
  }, [deviceId]);

  async function runIdentify() {
    if (!deviceId) return;

    setScanning(true);

    try {
      const result = await api.identify(deviceId);

      setReport(result);

      toast.success(
        result.recommended_adapter &&
          result.recommended_adapter !== "needs_selection"
          ? `Recovery method: ${recoveryAdapterLabel(result.recommended_adapter)}`
          : "Identification complete. Select a recovery method on Recovery.",
      );

      await refresh();
    } catch (err) {
      toast.error(
        err instanceof Error ? err.message : "Identification failed",
        { duration: Infinity },
      );
    } finally {
      setScanning(false);
    }
  }

  const flatStructure = useMemo(() => flattenNodes(structure), [structure]);

  const selectedEvidence = evidence.find((e) => e.id === deviceId);

  // A signature scan of an exported clip has no partition table and no recorder
  // filesystem, so disk-level hints and the recovery hand-off do not apply.
  const isClip =
    selectedEvidence?.media_type === "video_clip" ||
    selectedEvidence?.media_type === "logical_export";

  // On a clip, drop the filesystem / MBR pseudo-hit: a two-byte 0x55AA match in
  // an H.264 stream is not a partition table. Real container-signature vendor
  // hits are kept.
  const visibleHits = useMemo(() => {
    const hits = report?.hits ?? [];
    if (!isClip) return hits;
    return hits.filter(
      (h) =>
        h.vendor !== "Filesystem" &&
        h.capability_tier !== "filesystem_recovery",
    );
  }, [report, isClip]);

  return (
    <div className="flex flex-col gap-3">
      <PageHeader
        kicker="Step 2 · Identification"
        title="Device & format analysis"
        subtitle="Signature scan and partition layout. Picks the recovery adapter for the next step."
        actions={
          <Button
            disabled={!deviceId || scanning}
            onClick={() => void runIdentify()}
          >
            {scanning ? "Scanning…" : "Run identification"}
          </Button>
        }
      />

      {(selectedEvidence?.acquisition_class || report?.acquisition_class) && (
        <div
          role="alert"
          className="rounded-md border border-[var(--status-danger)] bg-[var(--status-danger-soft,transparent)] px-3 py-2 text-[13px] text-[var(--status-danger)]"
        >
          {selectedEvidence?.acquisition_class?.message ||
            report?.acquisition_class?.message ||
            "Builder image. Generated by this tool, not a field acquisition."}
        </div>
      )}

      {(selectedEvidence?.media_type === "video_clip" ||
        selectedEvidence?.media_type === "logical_export") && (
        <div className="rounded-md border border-[var(--border-subtle)] px-3 py-2 text-[13px] text-[var(--text-secondary)]">
          This is an exported clip, not a forensic disk image. There is no
          recorder filesystem to identify or deleted footage to recover. It can
          still be hashed, played back, run through Findings, and cross-camera
          traced. Identification below only checks for a vendor container
          signature.
        </div>
      )}

      {evidence.length === 0 ? (
        <section className="visily-card p-8 text-[13px] text-[var(--text-secondary)]">
          No evidence yet.{" "}
          <Link
            to={`/cases/${caseId}/acquire`}
            className="text-[var(--accent-500)] underline"
          >
            Acquire an image
          </Link>{" "}
          first.
        </section>
      ) : (
        <div className="grid min-h-[420px] gap-3 lg:grid-cols-[240px_1fr]">
          <section className="visily-card flex flex-col p-3">
            <p className="visily-card-title mb-2 text-[11px]">
              Evidence in this case
            </p>

            <ul className="space-y-1">
              {evidence.map((e) => (
                <li key={e.id}>
                  <button
                    type="button"

                    className={`w-full rounded-lg px-2 py-2 text-left ${
                      deviceId === e.id
                        ? "bg-[var(--accent-soft)] ring-1 ring-[var(--accent-500)]/30"
                        : "hover:bg-[var(--surface-3)]"
                    }`}

                    onClick={() => {
                      setDeviceId(e.id);

                      setReport(e.identification ?? null);

                      setHexOffset(0);
                    }}
                  >
                    <p className="truncate text-[12px] font-medium">
                      {e.filename}
                    </p>

                    <p className="mono mt-0.5 text-[10px] text-[var(--text-tertiary)]">
                      {formatBytes(e.size_bytes)}
                    </p>
                  </button>
                </li>
              ))}
            </ul>

            {!isClip && flatStructure.length > 0 ? (
              <>
                <p className="visily-card-title mb-2 mt-4 text-[11px]">
                  Layout tree{" "}
                  {flatStructure.length > LAYOUT_TREE_LIMIT ? (
                    <span className="font-normal text-[var(--text-tertiary)]">
                      (first {LAYOUT_TREE_LIMIT} of {flatStructure.length})
                    </span>
                  ) : null}
                </p>

                <div className="max-h-48 overflow-auto">
                  {flatStructure
                    .slice(0, LAYOUT_TREE_LIMIT)
                    .map(({ node, depth }) => (
                      <button
                        key={`${node.type}-${node.offset}-${node.label}`}

                        type="button"

                        className={`block w-full truncate rounded px-1 py-0.5 text-left text-[11px] ${
                          selectedNode?.offset === node.offset &&
                          selectedNode?.label === node.label
                            ? "bg-[var(--accent-soft)] text-[var(--accent-600)]"
                            : "hover:bg-[var(--surface-3)]"
                        }`}

                        style={{ paddingLeft: `${depth * 10 + 4}px` }}

                        onClick={() => {
                          setSelectedNode(node);

                          setHexOffset(node.offset);
                        }}
                      >
                        {node.label}
                      </button>
                    ))}
                </div>
              </>
            ) : null}
          </section>

          <div className="flex min-h-0 flex-col gap-3">
            <section className="visily-card p-4">
              <div className="flex flex-wrap items-start justify-between gap-3">
                <div>
                  <p className="visily-card-title text-[11px]">
                    Identification result
                  </p>

                  {selectedEvidence ? (
                    <p className="mt-1 text-[14px] font-semibold text-[var(--text-primary)]">
                      {selectedEvidence.filename}
                    </p>
                  ) : null}
                </div>

                {report?.recommended_adapter &&
                report.recommended_adapter !== "needs_selection" ? (
                  <span className="rounded-md bg-[var(--accent-soft)] px-3 py-1 text-[12px] font-semibold text-[var(--accent-700)]">
                    {recoveryAdapterLabel(report.recommended_adapter)}
                  </span>
                ) : null}
              </div>

              {!report ? (
                <p className="mt-4 text-[13px] text-[var(--text-tertiary)]">
                  Run identification to see vendor hits and adapter routing.
                </p>
              ) : visibleHits.length === 0 ? (
                <p className="mt-4 text-[13px] text-[var(--text-tertiary)]">
                  {isClip
                    ? "No vendor container signature in the sampled bytes. The clip can still be hashed, played back, and run through Findings and Cross-camera."
                    : "No vendor signature detected. This looks like generic or non-DVR footage. Select an adapter manually on Recovery, or continue with generic carving."}
                </p>
              ) : (
                <ul className="mt-4 space-y-2">
                  {visibleHits.map((hit) => (
                    <li
                      key={`${hit.vendor}-${hit.adapter}`}
                      className="rounded-lg border border-[var(--border-subtle)] px-3 py-2"
                    >
                      <div className="flex flex-wrap items-center justify-between gap-2">
                        <div>
                          <p className="text-[13px] font-semibold text-[var(--text-primary)]">
                            {hit.vendor}
                          </p>

                          <p className="text-[11px] text-[var(--text-tertiary)]">
                            {recoveryAdapterLabel(hit.adapter)}
                          </p>
                        </div>

                        <ConfidenceBadge
                          tier={
                            hit.confidence >= 0.8
                              ? "high"
                              : hit.confidence >= 0.5
                                ? "medium"
                                : "low"
                          }
                        />
                      </div>

                      {hit.markers.length > 0 ? (
                        <p className="mt-1 text-[11px] text-[var(--text-secondary)]">
                          Markers: {hit.markers.join(", ")}
                        </p>
                      ) : null}

                      {hit.capability_tier ? (
                        <p className="mt-1 text-[10px] font-bold uppercase tracking-wide text-[var(--accent-600)]">
                          {capabilityTierLabel(hit.capability_tier)}
                        </p>
                      ) : null}

                      {hit.validation_scope ? (
                        <p className="mt-0.5 text-[10px] text-[var(--text-tertiary)]">
                          {validationScopeLabel(hit.validation_scope)}
                        </p>
                      ) : null}
                    </li>
                  ))}
                </ul>
              )}

              {report?.oem_capabilities &&
              report.oem_capabilities.length > 0 ? (
                <div
                  className="mt-4 border-t pt-3"
                  style={{ borderColor: "var(--border-subtle)" }}
                >
                  <p className="text-[10px] font-bold uppercase tracking-wide text-[var(--text-tertiary)]">
                    Parser coverage across the {report.oem_capabilities.length}{" "}
                    vendors this build recognises
                  </p>
                  <div className="mt-2 overflow-x-auto">
                    <table className="w-full text-[11px]">
                      <thead>
                        <tr className="text-left text-[10px] uppercase text-[var(--text-tertiary)]">
                          <th className="pb-1 pr-3 font-medium">Vendor</th>
                          <th className="pb-1 pr-3 font-medium">Tier</th>
                          <th className="pb-1 font-medium">Scope</th>
                        </tr>
                      </thead>
                      <tbody>
                        {report.oem_capabilities.map((cap) => (
                          <tr
                            key={cap.vendor}
                            className="border-t"
                            style={{ borderColor: "var(--border-subtle)" }}
                          >
                            <td className="py-1 pr-3 font-medium text-[var(--text-primary)]">
                              {cap.vendor}
                            </td>
                            <td className="py-1 pr-3 text-[var(--text-secondary)]">
                              {capabilityTierLabel(cap.capability_tier)}
                            </td>
                            <td className="py-1 text-[var(--text-tertiary)]">
                              {validationScopeLabel(cap.validation_scope)}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              ) : null}

              {report ? (
                <div
                  className="mt-4 border-t pt-3"
                  style={{ borderColor: "var(--border-subtle)" }}
                >
                  <p className="text-[10px] font-bold uppercase tracking-wide text-[var(--text-tertiary)]">
                    Recorder identity
                  </p>
                  <dl className="mt-1.5 grid grid-cols-[auto_1fr] gap-x-3 gap-y-0.5 text-[11px]">
                    {(["Model", "Serial", "Firmware"] as const).map((field) => (
                      <div key={field} className="contents">
                        <dt className="text-[var(--text-tertiary)]">{field}</dt>
                        <dd className="text-[var(--text-secondary)]">
                          Not available from this image
                        </dd>
                      </div>
                    ))}
                  </dl>
                  <p className="mt-1.5 text-[10px] text-[var(--text-tertiary)]">
                    A signature scan reads container and filesystem markers, not
                    the recorder&rsquo;s device record.{" "}
                    {visibleHits.length > 0 ||
                    (!isClip && report.filesystem_hints.length > 0)
                      ? "Identification here is based on the markers listed above."
                      : "No vendor or filesystem marker was found in the sampled bytes."}
                  </p>
                </div>
              ) : null}

              {report && !isClip ? (
                <Button asChild className="mt-4" variant="secondary">
                  <Link to={`/cases/${caseId}/recover`}>
                    Continue to recovery →
                  </Link>
                </Button>
              ) : report && isClip ? (
                <p className="mt-4 text-[12px] text-[var(--text-secondary)]">
                  Recovery does not apply to an exported clip. Hash it, play it
                  back, run Findings, or trace it in Cross-camera.
                </p>
              ) : null}
            </section>

            <section className="visily-card flex min-h-0 flex-1 flex-col p-4">
              {deviceId ? (
                <HexViewer
                  deviceId={deviceId}
                  baseOffset={selectedNode?.offset ?? hexOffset}
                  title={`Hex at ${formatOffset(selectedNode?.offset ?? hexOffset)}`}
                />
              ) : (
                <p className="text-[13px] text-[var(--text-tertiary)]">
                  Select evidence to preview bytes.
                </p>
              )}

              {!isClip &&
              report?.filesystem_hints &&
              report.filesystem_hints.length > 0 ? (
                <div
                  className="mt-3 border-t pt-3"
                  style={{ borderColor: "var(--border-subtle)" }}
                >
                  <p className="text-[10px] font-bold uppercase text-[var(--text-tertiary)]">
                    Filesystem hints
                  </p>

                  <ul className="mt-1 space-y-0.5 font-mono text-[11px] text-[var(--text-secondary)]">
                    {report.filesystem_hints.map((h) => (
                      <li key={h.marker}>{h.label}</li>
                    ))}
                  </ul>
                </div>
              ) : null}

              {report?.coverage_note ? (
                <p className="mt-2 text-[11px] text-[var(--text-tertiary)]">
                  {report.coverage_note}
                </p>
              ) : null}
            </section>
          </div>
        </div>
      )}
    </div>
  );
}
